spring:
  datasource:
    url: jdbc:mysql://localhost/dateutil
    username: root
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
